# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "2.6"
  - "pypy"

install: 
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - py.test
